"""expandindo tabela ficha

Revision ID: 1f494555eb10
Revises: 937d75734bb7
Create Date: 2026-02-28 11:54:42.950197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f494555eb10'
down_revision = '937d75734bb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ficha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nomeguerra', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sexo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cpf', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sangue', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('endereco', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tel', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nomepai', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('telpai', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('nomemae', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('telmae', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('pessoaresp', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('parentesco', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('telresp', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('escola', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('serie', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('turnoescola', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('altura', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('peso', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pggoverno', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('expbmparente', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('nomeex', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('possui_observacoes', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('desloca_sozinho', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))
        batch_op.alter_column('possui_neurodivergencia',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=5),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ficha', schema=None) as batch_op:
        batch_op.alter_column('possui_neurodivergencia',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.drop_column('observacoes')
        batch_op.drop_column('desloca_sozinho')
        batch_op.drop_column('possui_observacoes')
        batch_op.drop_column('nomeex')
        batch_op.drop_column('expbmparente')
        batch_op.drop_column('pggoverno')
        batch_op.drop_column('peso')
        batch_op.drop_column('altura')
        batch_op.drop_column('turnoescola')
        batch_op.drop_column('serie')
        batch_op.drop_column('escola')
        batch_op.drop_column('telresp')
        batch_op.drop_column('parentesco')
        batch_op.drop_column('pessoaresp')
        batch_op.drop_column('telmae')
        batch_op.drop_column('nomemae')
        batch_op.drop_column('telpai')
        batch_op.drop_column('nomepai')
        batch_op.drop_column('email')
        batch_op.drop_column('tel')
        batch_op.drop_column('endereco')
        batch_op.drop_column('sangue')
        batch_op.drop_column('cpf')
        batch_op.drop_column('sexo')
        batch_op.drop_column('nomeguerra')

    # ### end Alembic commands ###
