"""criando tabelas

Revision ID: 937d75734bb7
Revises: 
Create Date: 2026-02-28 11:29:56.500971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937d75734bb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ficha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('datanascimento', sa.Date(), nullable=True),
    sa.Column('situacao', sa.String(length=10), nullable=True),
    sa.Column('turnopbm', sa.String(length=50), nullable=True),
    sa.Column('localpbm', sa.String(length=100), nullable=True),
    sa.Column('rotaonibus', sa.String(length=100), nullable=True),
    sa.Column('possui_neurodivergencia', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('senha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('nivel', sa.String(length=10), nullable=False),
    sa.Column('obm', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('senha')
    op.drop_table('ficha')
    # ### end Alembic commands ###
