"""criando tabela chamada_diaria

Revision ID: b48a0c4e7ec0
Revises: d70ce8dbbcf4
Create Date: 2026-02-28 12:34:11.153012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b48a0c4e7ec0'
down_revision = 'd70ce8dbbcf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chamada_diaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idmatricula', sa.Integer(), nullable=True),
    sa.Column('data_chamada', sa.Date(), nullable=True),
    sa.Column('presenca', sa.Boolean(), nullable=True),
    sa.Column('turno', sa.String(length=20), nullable=True),
    sa.Column('pelotao', sa.Integer(), nullable=True),
    sa.Column('obm', sa.String(length=100), nullable=True),
    sa.Column('usuario_registro', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['idmatricula'], ['ficha.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chamada_diaria')
    # ### end Alembic commands ###
