"""adicionando campos completos ficha

Revision ID: d70ce8dbbcf4
Revises: 1f494555eb10
Create Date: 2026-02-28 12:13:40.778521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd70ce8dbbcf4'
down_revision = '1f494555eb10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ficha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graduacao', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('numero_uniforme', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('numero_calcado', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('dias_suspensao', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data_inicio_suspensao', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('dataregistro', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('dataalteracao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('foto', sa.String(length=150), nullable=True))
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('nomeguerra',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('endereco',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('turnopbm',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('nomepai',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('nomemae',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('pessoaresp',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('escola',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('serie',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('turnoescola',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('situacao',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('sangue',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.drop_column('altura')
        batch_op.drop_column('nomeex')
        batch_op.drop_column('expbmparente')
        batch_op.drop_column('tel')
        batch_op.drop_column('peso')
        batch_op.drop_column('pggoverno')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ficha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pggoverno', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('peso', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tel', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('expbmparente', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nomeex', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('altura', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('sangue',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('situacao',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('turnoescola',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('serie',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('escola',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('pessoaresp',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('nomemae',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('nomepai',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('turnopbm',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('endereco',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('nomeguerra',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('foto')
        batch_op.drop_column('dataalteracao')
        batch_op.drop_column('dataregistro')
        batch_op.drop_column('data_inicio_suspensao')
        batch_op.drop_column('dias_suspensao')
        batch_op.drop_column('numero_calcado')
        batch_op.drop_column('numero_uniforme')
        batch_op.drop_column('graduacao')

    # ### end Alembic commands ###
